### ISSUE TITLE
changing nth letter in word 

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project2#339]
I'm trying to change the nth letter in my brand name.  Basically every capital letter i want to be pink.  I tried using ::first-letter class and separating the word into multiple parts but they won't all stay in one line.  I saw online that maybe this can be done with jquery, but I was wondering if there is an easier way.    

``` html
<p class="navbar-brand logo" id ="brandname">ReadyPlayerTwoDating </p>

```

``` css
  .logo::first-letter{
    font-weight: bold;
    color: #ff0066;
  }
```
