### ISSUE TITLE
issue with home page loading

### ISSUE THREAD

**Issue by jkoul** [ga-wdi-exercises/project2#71]
I tried to set my home page to a "home#index" class and included a "home_controller.rb" file and a corresponding route, but it's not linking to the layout.erb file when it loads.

Help!

**Comment by jshawl** [comment]
layout.erb was used in sinatra. In rails, check `views/layouts/application.html.erb`

**Comment by jkoul** [comment]
Yes to clarify that's what it should be linking to. Doesn't it do so automatically from any file within the appropriate path of the "views" folder?

**Comment by RobertAKARobin** [comment]
If your `application.html.erb` contains `<%= yield %>`, then yes, all of your views should be rendered within that layout.

**Comment by jkoul** [comment]
That's why I'm confused. It works for every other page but not that one.

**Comment by RobertAKARobin** [comment]
Can you be more specific about what happens when it loads?

**Comment by jkoul** [comment]
Only the text specified by the views/home/index.html.erb page loads

**Comment by RobertAKARobin** [comment]
Can you push your code to Github so I can take a look?

**Comment by jkoul** [comment]
https://github.com/jkoul/dcfuture/

**Comment by RobertAKARobin** [comment]
Thanks! The problem is that your `home_controller.rb` is inheriting from `ActionController::Base`. The only thing that should do that is your `application_controller.rb`. Everything else should inherit from `ApplicationController`.

An unrelated issue: your database is SQLite instead of Postgresql. This means you forgot to add the `-d postgresql` when you did `rails new`. This means you'll be unable to deploy to Heroku. To fix this, `rails new appname -d postgresql` elsewhere on your computer, and then copy over `db/migrate`, `db/seeds.rb`, `config/routes.rb`, and everything in the `app` directory.

Neat styling!

**Comment by RobertAKARobin** [comment]
Alternatively, replace your `config/database.yml` with this:

```
development:
  adapter: postgresql
  encoding: utf8
  database: dcfuture_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: dcfuture_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: dcfuture_production
  pool: 5
  username:
  password:
```

Remove this in your `Gemfile`:

```
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
```

...and replace that line with this:

```
gem 'pg'
```

Then `bundle install`, `rake db:create`, `rake db:migrate`, `rake db:seed`, etc.
