### ISSUE TITLE
issue with deploying to heroku

### ISSUE THREAD

**Issue by msteffan** [ga-wdi-exercises/project2#95]
I tried to deploy my project to Heroku to test it, but the heroku push command returned the following error:
![screen shot 2015-08-04 at 7 45 49 pm](https://cloud.githubusercontent.com/assets/7719096/9075444/ca7050b6-3ae2-11e5-90fc-ac7de35e5691.png)

I followed the instructions that the error gave and then removed all references to sqlite from the project; I also followed the instructions on the heroku website to remove other gems that possibly had sqlite dependencies. Finally, I worked to troubleshoot it with Eddie & Stephen, but it still will not push to heroku. What else could I try?
![screen shot 2015-08-04 at 7 53 43 pm](https://cloud.githubusercontent.com/assets/7719096/9075455/f645a1f0-3ae2-11e5-8bac-163966f1d490.png)

Here is what my database.yml file looks like:
![screen shot 2015-08-04 at 7 58 10 pm](https://cloud.githubusercontent.com/assets/7719096/9075480/4d0b0f52-3ae3-11e5-842f-2995421c06b3.png)

**Comment by RobertAKARobin** [comment]
Oh, man. Most annoying error ever. It comes from having done `rails new tinboard` instead of `rails new tinboard -d postgresql`. Try this:

First, replace your `config/database.yml` with this:

```
development:
  adapter: postgresql
  encoding: utf8
  database: tinboard_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: tinboard_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: tinboard_production
  pool: 5
  username:
  password:
```

Second, remove this in your `Gemfile`:

```
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
```

...and replace that line with this:

```
gem 'pg'
```

Third, `bundle install` to change things locally.

Fourth, push back to Heroku.

If **that** doesn't work, let me know!
